name: Build_Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Run flake8
      run:
        flake8 .
  
  test:
    steps:
    - uses: actions/checkout@v2
    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install .
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v candle/tests/
