name: Build_Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CANDLE_DATA_DIR: "/tmp/"

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install flake8
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pytest
        run: |
          pip install pytest
      - name: Install frameworks
        run: |
          pip install tensorflow==2.7.1
          pip install torch==1.10.2+cpu torchvision==0.11.3+cpu torchaudio==0.10.2+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install pandas==1.4.0 scikit-learn==1.0.2 numpy==1.21.5
      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install .
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v candle/tests/
